server:
  port: 9891
## spring
spring:
  application:
    name: sharding-sphere
  profiles:
    active: dev

## mybatis-plus
mybatis-plus:
  mapper-locations: classpath:/mapper/**.xml
  type-aliases-package: com.framework.shardingsphere.entity
  configuration:
    # MyBatis 配置
    map-underscore-to-camel-case: true
    global-config:
      # 全局配置
      db-config:
        # 数据库配置
        id-type: auto
