dataSources:
  ds0:
    dataSourceClassName: com.zaxxer.hikari.HikariDataSource
    driverClassName: com.mysql.cj.jdbc.Driver
    jdbcUrl: jdbc:mysql://127.0.0.1:3306/sharding-sphere?characterEncoding=utf8&useAffectedRows=true&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: root
    password: 12345678

rules:
  - !SHARDING
    tables:
      #表名
      router_config:
        #数据节点，所有表名
        actualDataNodes: ds0.router_config_0$->{0..9},ds0.router_config_$->{10..49}
        #分表策略
        tableStrategy:
          #分表类型，单列作为分表键
          standard:
            shardingColumn: id #分表列
            shardingAlgorithmName: id-suffix-mode-50 #分表算法名称，与下面对应
    shardingAlgorithms: # 分片算法配置
      id-suffix-mode-50:
        type: INLINE # 基于行表达式的分片算法
        props:
          #分片表达式，groovy 脚本
          algorithm-expression: router_config_$->{String.valueOf(Long.parseLong(String.valueOf(id).substring(String.valueOf(id).size() - 2)) % 50 ).padLeft(2,'0')}

props:
  sql-show: true


# algorithm-expression 报错 Long.parseLong(member_id)
# shardingsphere-springboot-starter 不再维护
# shardingAlgorithms 只提供了 INLINE
